data:
  base_dir: "C:/Users/moury/OneDrive/Desktop/RADBOUD/THESIS/Data/PECTUS-DICOMS"
  dicom_dir: "C:/Users/moury/OneDrive/Desktop/RADBOUD/THESIS/Data/PECTUS-DICOMS/ABW-ARU/ABW-ARU-0001"
  annotation_excel: "C:/Users/moury/OneDrive/Desktop/RADBOUD/THESIS/Data/CC_Annotations_M.xlsx"
  image_size: 512

model:
  backbone: "efficientnet_b0"
  num_classes: 2
  pretrained: true

training:
  epochs: 1
  batch_size: 2
  learning_rate: 0.0001
  val_split: 0.2
  seed: 42

loss:
  type: "focal"
  gamma: 2.0
  alpha: 0.75

output_dir: "outputs/classifier"